<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="21276" started-at="2022-05-18T12:57:01Z" finished-at="2022-05-18T12:57:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21276" started-at="2022-05-18T12:57:01Z" finished-at="2022-05-18T12:57:22Z">
      <class name="com.selenium.pom.TestCases.LoginTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.selenium.pom.TestCases.LoginTest@57baeedf]" name="beforeSuite" is-config="true" duration-ms="8691" started-at="2022-05-18T18:26:52Z" finished-at="2022-05-18T18:27:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.selenium.pom.TestCases.LoginTest@57baeedf]" name="beforeMethod" is-config="true" duration-ms="539" started-at="2022-05-18T18:27:03Z" finished-at="2022-05-18T18:27:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.selenium.pom.TestCases.LoginTest.searchFlights(java.util.HashMap) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="searchFlights(java.util.HashMap)[pri:0, instance:com.selenium.pom.TestCases.LoginTest@57baeedf]" name="searchFlights" duration-ms="17571" started-at="2022-05-18T18:27:04Z" data-provider="SearchFlightsDP" finished-at="2022-05-18T18:27:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{TestData3=, Description=SearchFlightsDP, UserName=mercury, TestData9=, TestData8=, TestData5=, TestData4=, PassWord=mercury, TestData7=, FromLocation=DEL, TestData6=, ExpectedResult=Find a Flight:, TC_ID=TC01, ToLocation=BER}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [MakeMyTrip] but found [Find a Flight:]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [MakeMyTrip] but found [Find a Flight:]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.selenium.pom.TestCases.LoginTest.searchFlights(LoginTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchFlights -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.selenium.pom.TestCases.LoginTest@57baeedf]" name="afterMethod" is-config="true" duration-ms="930" started-at="2022-05-18T18:27:21Z" finished-at="2022-05-18T18:27:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=searchFlights status=FAILURE method=LoginTest.searchFlights(java.util.HashMap)[pri:0, instance:com.selenium.pom.TestCases.LoginTest@57baeedf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.selenium.pom.TestCases.LoginTest@57baeedf]" name="afterSuite" is-config="true" duration-ms="1048" started-at="2022-05-18T18:27:22Z" finished-at="2022-05-18T18:27:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.selenium.pom.TestCases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
